export const mockData = [
  {
    id: 'YCO',
    name: 'Kugluktuk Airport',
    rule: 'CA-NU',
    status: 'NA',
    other: 'CA',
    example: 'CYCO',
  },
  {
    id: 'AID',
    name: 'Anderson Municipal Darlington Field',
    rule: 'US-IN',
    status: 'NA',
    other: 'US',
    example: 'KAID',
  },
  {
    id: 'RUA',
    name: 'Arua Airport',
    rule: 'UG-303',
    status: 'AF',
    other: 'UG',
    example: 'HUAR',
  },
  {
    id: 'UDD',
    name: 'Bermuda Dunes Airport',
    rule: 'US-CA',
    status: 'NA',
    other: 'US',
    example: 'KUDD',
  },
  {
    id: 'KLQ',
    name: 'Keluang Airport',
    rule: 'ID-SS',
    status: 'AS',
    other: 'ID',
    example: 'WIPV',
  },
  {
    id: 'ATE',
    name: 'Antlers Municipal Airport',
    rule: 'US-OK',
    status: 'NA',
    other: 'US',
    example: '80F',
  },
  {
    id: 'QSC',
    name: 'Mário Pereira Lopes–São Carlos Airport',
    rule: 'BR-SP',
    status: 'SA',
    other: 'BR',
    example: 'SDSC',
  },
  {
    id: 'ELB',
    name: 'Las Flores Airport',
    rule: 'CO-MAG',
    status: 'SA',
    other: 'CO',
    example: 'SKBC',
  },
  {
    id: 'IHN',
    name: 'Qishn Airport',
    rule: 'YE-MR',
    status: 'AS',
    other: 'YE',
    example: 'OYQN',
  },
  {
    id: 'PZO',
    name: 'General Manuel Carlos Piar International Airport',
    rule: 'VE-F',
    status: 'SA',
    other: 'VE',
    example: 'SVPR',
  },
  {
    id: 'MTQ',
    name: 'Mitchell Airport',
    rule: 'AU-QLD',
    status: 'OC',
    other: 'AU',
    example: 'YMIT',
  },
  {
    id: '0',
    name: 'Santa Paula Airport',
    rule: 'BR-SP',
    status: 'SA',
    other: 'BR',
    example: 'SISP',
  },
  {
    id: 'LNP',
    name: 'Lonesome Pine Airport',
    rule: 'US-VA',
    status: 'NA',
    other: 'US',
    example: 'KLNP',
  },
  {
    id: 'REO',
    name: 'Rome State Airport',
    rule: 'US-OR',
    status: 'NA',
    other: 'US',
    example: 'KREO',
  },
  {
    id: 'CJL',
    name: 'Chitral Airport',
    rule: 'PK-NW',
    status: 'AS',
    other: 'PK',
    example: 'OPCH',
  },
  {
    id: 'GFN',
    name: 'Grafton Airport',
    rule: 'AU-NSW',
    status: 'OC',
    other: 'AU',
    example: 'YGFN',
  },
  {
    id: 'CAG',
    name: 'Cagliari Elmas Airport',
    rule: 'IT-88',
    status: 'EU',
    other: 'IT',
    example: 'LIEE',
  },
  {
    id: 'SIO',
    name: 'Smithton Airport',
    rule: 'AU-TAS',
    status: 'OC',
    other: 'AU',
    example: 'YSMI',
  },
  {
    id: 'BVA',
    name: 'Paris Beauvais Tillé Airport',
    rule: 'FR-S',
    status: 'EU',
    other: 'FR',
    example: 'LFOB',
  },
  {
    id: 'OPU',
    name: 'Balimo Airport',
    rule: 'PG-WPD',
    status: 'OC',
    other: 'PG',
    example: 'AYBM',
  },
  {
    id: 'LEV',
    name: 'Levuka Airfield',
    rule: 'FJ-E',
    status: 'OC',
    other: 'FJ',
    example: 'NFNB',
  },
  {
    id: 'WSY',
    name: 'Whitsunday Island Airport',
    rule: 'AU-QLD',
    status: 'OC',
    other: 'AU',
    example: 'YWHI',
  },
  {
    id: 'GLB',
    name: 'San Carlos Apache Airport',
    rule: 'US-AZ',
    status: 'NA',
    other: 'US',
    example: 'P13',
  },
  {
    id: 'PKX',
    name: 'Beijing Daxing International Airport',
    rule: 'CN-13',
    status: 'AS',
    other: 'CN',
    example: 'ZBAD',
  },
  {
    id: 'AYC',
    name: 'Ayacucho Airport',
    rule: 'CO-CES',
    status: 'SA',
    other: 'CO',
    example: null,
  },
  {
    id: 'CFO',
    name: 'Confresa Airport',
    rule: 'BR-MT',
    status: 'SA',
    other: 'BR',
    example: 'SJHG',
  },
  {
    id: 'LTW',
    name: "St. Mary's County Regional Airport",
    rule: 'US-MD',
    status: 'NA',
    other: 'US',
    example: '2W6',
  },
  {
    id: 'CVB',
    name: 'Chungribu Airport',
    rule: 'PG-MPM',
    status: 'OC',
    other: 'PG',
    example: 'AYCB',
  },
  {
    id: 'UPR',
    name: 'Upiara Airport',
    rule: 'PG-WPD',
    status: 'OC',
    other: 'PG',
    example: 'AYUR',
  },
  {
    id: 'LDH',
    name: 'Lord Howe Island Airport',
    rule: 'AU-NSW',
    status: 'OC',
    other: 'AU',
    example: 'YLHI',
  },
  {
    id: 'TCJ',
    name: 'Torembi Airport',
    rule: 'PG-ESW',
    status: 'OC',
    other: 'PG',
    example: 'AYVM',
  },
  {
    id: 'LUS',
    name: 'Lusanga Airport',
    rule: 'CD-BN',
    status: 'AF',
    other: 'CD',
    example: 'FZCE',
  },
  {
    id: 'AAB',
    name: 'Arrabury Airport',
    rule: 'AU-QLD',
    status: 'OC',
    other: 'AU',
    example: 'YARY',
  },
  {
    id: 'HUL',
    name: 'Houlton International Airport',
    rule: 'US-ME',
    status: 'NA',
    other: 'US',
    example: 'KHUL',
  },
  {
    id: 'MHV',
    name: 'Mojave Airport',
    rule: 'US-CA',
    status: 'NA',
    other: 'US',
    example: 'KMHV',
  },
  {
    id: 'VAK',
    name: 'Chevak Airport',
    rule: 'US-AK',
    status: 'NA',
    other: 'US',
    example: 'PAVA',
  },
  {
    id: 'SVB',
    name: 'Sambava Airport',
    rule: 'MG-D',
    status: 'AF',
    other: 'MG',
    example: 'FMNS',
  },
  {
    id: 'OML',
    name: 'Omkalai Airport',
    rule: 'PG-CPK',
    status: 'OC',
    other: 'PG',
    example: null,
  },
  {
    id: 'OHI',
    name: 'Oshakati Airport',
    rule: 'NA-ON',
    status: 'AF',
    other: 'NA',
    example: 'FYOS',
  },
  {
    id: 'SOB',
    name: 'Sármellék International Airport',
    rule: 'HU-ZA',
    status: 'EU',
    other: 'HU',
    example: 'LHSM',
  },
  {
    id: 'CAT',
    name: 'Cascais Airport',
    rule: 'PT-11',
    status: 'EU',
    other: 'PT',
    example: 'LPCS',
  },
  {
    id: 'LRS',
    name: 'Leros Airport',
    rule: 'GR-81',
    status: 'EU',
    other: 'GR',
    example: 'LGLE',
  },
  {
    id: 'YRV',
    name: 'Revelstoke Airport',
    rule: 'CA-BC',
    status: 'NA',
    other: 'CA',
    example: 'CYRV',
  },
  {
    id: 'RZR',
    name: 'Ramsar Airport',
    rule: 'IR-21',
    status: 'AS',
    other: 'IR',
    example: 'OINR',
  },
  {
    id: 'AUN',
    name: 'Auburn Municipal Airport',
    rule: 'US-CA',
    status: 'NA',
    other: 'US',
    example: 'KAUN',
  },
  {
    id: 'YSJ',
    name: 'Saint John Airport',
    rule: 'CA-NB',
    status: 'NA',
    other: 'CA',
    example: 'CYSJ',
  },
  {
    id: 'WAK',
    name: 'Ankazoabo Airport',
    rule: 'MG-U',
    status: 'AF',
    other: 'MG',
    example: 'FMSZ',
  },
  {
    id: 'AKP',
    name: 'Anaktuvuk Pass Airport',
    rule: 'US-AK',
    status: 'NA',
    other: 'US',
    example: 'PAKP',
  },
  {
    id: 'KCB',
    name: 'Tepoe Airstrip',
    rule: 'SR-SI',
    status: 'SA',
    other: 'SR',
    example: 'SMTP',
  },
  {
    id: 'DBA',
    name: 'Dalbandin Airport',
    rule: 'PK-BA',
    status: 'AS',
    other: 'PK',
    example: 'OPDB',
  },
  {
    id: 'MZB',
    name: 'Mocímboa da Praia Airport',
    rule: 'MZ-P',
    status: 'AF',
    other: 'MZ',
    example: 'FQMP',
  },
  {
    id: 'KBR',
    name: 'Sultan Ismail Petra Airport',
    rule: 'MY-03',
    status: 'AS',
    other: 'MY',
    example: 'WMKC',
  },
  {
    id: 'IKS',
    name: 'Tiksi Airport',
    rule: 'RU-SA',
    status: 'AS',
    other: 'RU',
    example: 'UEST',
  },
  {
    id: 'SYU',
    name: 'Warraber Island Airport',
    rule: 'AU-QLD',
    status: 'OC',
    other: 'AU',
    example: 'YWBS',
  },
  {
    id: 'MLZ',
    name: 'Cerro Largo International Airport',
    rule: 'UY-CL',
    status: 'SA',
    other: 'UY',
    example: 'SUMO',
  },
  {
    id: 'HTO',
    name: 'East Hampton Airport',
    rule: 'US-NY',
    status: 'NA',
    other: 'US',
    example: 'KHTO',
  },
  {
    id: 'YCS',
    name: 'Chesterfield Inlet Airport',
    rule: 'CA-NU',
    status: 'NA',
    other: 'CA',
    example: 'CYCS',
  },
  {
    id: 'KST',
    name: 'Kosti Airport',
    rule: 'SD-08',
    status: 'AF',
    other: 'SD',
    example: 'HSKI',
  },
  {
    id: 'JJU',
    name: 'Qaqortoq Heliport',
    rule: 'GL-U-A',
    status: 'NA',
    other: 'GL',
    example: 'BGJH',
  },
  {
    id: 'HND',
    name: 'Tokyo Haneda International Airport',
    rule: 'JP-13',
    status: 'AS',
    other: 'JP',
    example: 'RJTT',
  },
  {
    id: 'NOD',
    name: 'Norden-Norddeich Airport',
    rule: 'DE-NI',
    status: 'EU',
    other: 'DE',
    example: 'EDWS',
  },
  {
    id: 'LQM',
    name: 'Caucaya Airport',
    rule: 'CO-PUT',
    status: 'SA',
    other: 'CO',
    example: 'SKLG',
  },
  {
    id: 'APK',
    name: 'Apataki Airport',
    rule: 'PF-U-A',
    status: 'OC',
    other: 'PF',
    example: 'NTGD',
  },
  {
    id: 'ICR',
    name: 'Nicaro Airport',
    rule: 'CU-11',
    status: 'NA',
    other: 'CU',
    example: 'MUNC',
  },
  {
    id: 'BWQ',
    name: 'Brewarrina Airport',
    rule: 'AU-NSW',
    status: 'OC',
    other: 'AU',
    example: 'YBRW',
  },
  {
    id: 'SJO',
    name: 'Juan Santamaria International Airport',
    rule: 'CR-A',
    status: 'NA',
    other: 'CR',
    example: 'MROC',
  },
  {
    id: 'WBO',
    name: 'Antsoa Airport',
    rule: 'MG-U',
    status: 'AF',
    other: 'MG',
    example: 'FMSB',
  },
  {
    id: 'LEO',
    name: 'Lekoni Airport',
    rule: 'GA-2',
    status: 'AF',
    other: 'GA',
    example: null,
  },
  {
    id: 'SLU',
    name: 'George F. L. Charles Airport',
    rule: 'LC-02',
    status: 'NA',
    other: 'LC',
    example: 'TLPC',
  },
  {
    id: 'KDL',
    name: 'Kärdla Airport',
    rule: 'EE-39',
    status: 'EU',
    other: 'EE',
    example: 'EEKA',
  },
  {
    id: 'PNP',
    name: 'Girua Airport',
    rule: 'PG-NPP',
    status: 'OC',
    other: 'PG',
    example: 'AYGR',
  },
  {
    id: 'LBS',
    name: 'Labasa Airport',
    rule: 'FJ-N',
    status: 'OC',
    other: 'FJ',
    example: 'NFNL',
  },
  {
    id: 'MWO',
    name: 'Middletown Regional Airport',
    rule: 'US-OH',
    status: 'NA',
    other: 'US',
    example: 'KMWO',
  },
  {
    id: 'BBZ',
    name: 'Zambezi Airport',
    rule: 'ZM-06',
    status: 'AF',
    other: 'ZM',
    example: 'FLZB',
  },
  {
    id: 'AHF',
    name: 'Arapahoe Municipal Airport',
    rule: 'US-NE',
    status: 'NA',
    other: 'US',
    example: null,
  },
  {
    id: 'SMD',
    name: 'Smith Field',
    rule: 'US-IN',
    status: 'NA',
    other: 'US',
    example: 'KSMD',
  },
  {
    id: 'GTR',
    name: 'Golden Triangle Regional Airport',
    rule: 'US-MS',
    status: 'NA',
    other: 'US',
    example: 'KGTR',
  },
  {
    id: 'ABO',
    name: 'Aboisso Airport',
    rule: 'CI-13',
    status: 'AF',
    other: 'CI',
    example: 'DIAO',
  },
  {
    id: 'RRT',
    name: 'Warroad International Memorial Airport',
    rule: 'US-MN',
    status: 'NA',
    other: 'US',
    example: 'KRRT',
  },
  {
    id: 'COI',
    name: 'Merritt Island Airport',
    rule: 'US-FL',
    status: 'NA',
    other: 'US',
    example: 'KCOI',
  },
  {
    id: 'MUW',
    name: 'Ghriss Airport',
    rule: 'DZ-29',
    status: 'AF',
    other: 'DZ',
    example: 'DAOV',
  },
  {
    id: 'CHC',
    name: 'Christchurch International Airport',
    rule: 'NZ-CAN',
    status: 'OC',
    other: 'NZ',
    example: 'NZCH',
  },
  {
    id: 'PON',
    name: 'Poptún Airport',
    rule: 'GT-PE',
    status: 'NA',
    other: 'GT',
    example: 'MGPP',
  },
  {
    id: 'LMD',
    name: 'Los Menucos Airport',
    rule: 'AR-R',
    status: 'SA',
    other: 'AR',
    example: null,
  },
  {
    id: 'MSN',
    name: 'Dane County Regional Truax Field',
    rule: 'US-WI',
    status: 'NA',
    other: 'US',
    example: 'KMSN',
  },
  {
    id: 'HED',
    name: 'Herendeen Bay Airport',
    rule: 'US-AK',
    status: 'NA',
    other: 'US',
    example: 'AK33',
  },
  {
    id: 'INC',
    name: 'Yinchuan Hedong International Airport',
    rule: 'CN-64',
    status: 'AS',
    other: 'CN',
    example: 'ZLIC',
  },
  {
    id: 'DNP',
    name: 'Tulsipur Airport',
    rule: 'NP-RA',
    status: 'AS',
    other: 'NP',
    example: 'VNDG',
  },
  {
    id: 'RAT',
    name: 'Raduzhny Airport',
    rule: 'RU-KHM',
    status: 'AS',
    other: 'RU',
    example: 'USNR',
  },
  {
    id: 'RJI',
    name: 'Rajouri Airport',
    rule: 'IN-JK',
    status: 'AS',
    other: 'IN',
    example: null,
  },
  {
    id: 'DLN',
    name: 'Dillon Airport',
    rule: 'US-MT',
    status: 'NA',
    other: 'US',
    example: 'KDLN',
  },
  {
    id: 'EOI',
    name: 'Eday Airport',
    rule: 'GB-SCT',
    status: 'EU',
    other: 'GB',
    example: 'EGED',
  },
  {
    id: 'SFB',
    name: 'Orlando Sanford International Airport',
    rule: 'US-FL',
    status: 'NA',
    other: 'US',
    example: 'KSFB',
  },
  {
    id: 'KGR',
    name: 'Kulgera Airport',
    rule: 'AU-NT',
    status: 'OC',
    other: 'AU',
    example: null,
  },
  {
    id: 'MJR',
    name: 'Miramar Airport',
    rule: 'AR-B',
    status: 'SA',
    other: 'AR',
    example: 'SAEM',
  },
  {
    id: 'PDE',
    name: 'Pandie Pandie Airport',
    rule: 'AU-SA',
    status: 'OC',
    other: 'AU',
    example: 'YPDI',
  },
  {
    id: 'TNS',
    name: 'Tungsten (Cantung) Airport',
    rule: 'CA-NT',
    status: 'NA',
    other: 'CA',
    example: 'CBX5',
  },
  {
    id: 'KBC',
    name: 'Birch Creek Airport',
    rule: 'US-AK',
    status: 'NA',
    other: 'US',
    example: 'Z91',
  },
  {
    id: 'PUP',
    name: 'Po Airport',
    rule: 'BF-NAO',
    status: 'AF',
    other: 'BF',
    example: 'DFCP',
  },
];
